### ISSUE TITLE
Crash on CropGrowEvent in interaction between this mod and Bloom and Gloom / Atmospheric

### ISSUE THREAD

**Issue by Nick-McKay** [CorgiTaco/Better-Weather#14]
[05Jan2021 13:08:36.385] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[6, 7, 8]} to 2 on Block{atmospheric:tall_aloe_vera}, it is not an allowed value
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class corgitaco.betterweather.BetterWeather$BetterWeatherEvents cropGrowEventPre(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Pre;)V
		2: ASM: class mod.schnappdragon.bloom_and_gloom.core.event.BGEvents onBlockEvent(Lnet/minecraftforge/event/world/BlockEvent;)V
java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[6, 7, 8]} to 2 on Block{atmospheric:tall_aloe_vera}, it is not an allowed value
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:122)
	at corgitaco.betterweather.BetterWeather$BetterWeatherEvents.cropGrowEventPre(BetterWeather.java:194)
	at net.minecraftforge.eventbus.ASMEventHandler_214_BetterWeatherEvents_cropGrowEventPre_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPre(ForgeHooks.java:1008)
	at com.minecraftabnormals.atmospheric.common.block.AloeVeraTallBlock.func_225534_a_(AloeVeraTallBlock.java:194)
	at net.minecraft.block.AbstractBlock.func_225542_b_(AbstractBlock.java:287)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:622)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:696)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[05Jan2021 13:08:36.387] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID fcd9f9f3-f97e-4a15-8af2-b8cb03624231
[05Jan2021 13:08:36.393] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[6, 7, 8]} to 2 on Block{atmospheric:tall_aloe_vera}, it is not an allowed value
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:122) ~[?:?]
	at corgitaco.betterweather.BetterWeather$BetterWeatherEvents.cropGrowEventPre(BetterWeather.java:194) ~[betterweather:1.1.1]
	at net.minecraftforge.eventbus.ASMEventHandler_214_BetterWeatherEvents_cropGrowEventPre_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onCropsGrowPre(ForgeHooks.java:1008) ~[forge:?]
	at com.minecraftabnormals.atmospheric.common.block.AloeVeraTallBlock.func_225534_a_(AloeVeraTallBlock.java:194) ~[atmospheric:3.0.0]
	at net.minecraft.block.AbstractBlock.func_225542_b_(AbstractBlock.java:287) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:622) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:696) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	... 5 more

**Comment by officiallyunfunny** [comment]
Hello,
I also get the same issue in my mod pack and It was Atmospheric mod that crashed for me

**Comment by CorgiTaco** [comment]
Should be fixed: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3161729
