### ISSUE TITLE
world crash unfixable

### ISSUE THREAD

**Issue by spinnerX49** [CorgiTaco/Better-Weather#5]
I had a blizzard on and tp somewhere crashed me. after copying "/betterweather clear" it cleared it but after 5 seconds game crash. the world was a test world so thats fine but I dont want to have that risk in my main world uninstalling till fixed

**Comment by CorgiTaco** [comment]
It'd be appreciated if you could leave me with a crashlog and a latest.log instead saying "oh my server crashed"

**Comment by spinnerX49** [comment]
oh yeah forgot about that here "Time: 10/26/20 9:39 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$5033/1162983770.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_3898.method_17225(class_3898.java:579)
	at net.minecraft.class_3898$$Lambda$5109/878841038.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$5106/1119529941.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 12 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3301.method_15930(class_3301.java:18)
	at net.minecraft.class_3301.method_14452(class_3301.java:11)
	at net.minecraft.class_3284.method_15927(class_3284.java:90)
	at net.minecraft.class_3243.method_14358(class_3243.java:28)
	at net.minecraft.class_2988.method_12892(class_2988.java:20)
	at net.minecraft.class_2988.method_13151(class_2988.java:13)
	at net.minecraft.class_2975.method_12862(class_2975.java:44)
	at net.minecraft.class_1959.method_8702(class_1959.java:575)
	at net.minecraft.class_2794.method_12102(class_2794.java:210)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$1797/1224339926.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	... 17 more"

**Comment by spinnerX49** [comment]
tried my other worlds all corupt and cant make a new world ava.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3301.method_15930(class_3301.java:18)
	at net.minecraft.class_3301.method_14452(class_3301.java:11)
	at net.minecraft.class_3284.method_15927(class_3284.java:90)
	at net.minecraft.class_3243.method_14358(class_3243.java:28)
	at net.minecraft.class_2988.method_12892(class_2988.java:20)
	at net.minecraft.class_2988.method_13151(class_2988.java:13)
	at net.minecraft.class_2975.method_12862(class_2975.java:44)
	at net.minecraft.class_1959.method_8702(class_1959.java:575)
	at net.minecraft.class_2794.method_12102(class_2794.java:210)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$1796/1804934885.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$4994/1093055106.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$4979/349904103.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$4992/1457885555.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_3301.method_15930(class_3301.java:18)
	at net.minecraft.class_3301.method_14452(class_3301.java:11)
	at net.minecraft.class_3284.method_15927(class_3284.java:90)
	at net.minecraft.class_3243.method_14358(class_3243.java:28)
	at net.minecraft.class_2988.method_12892(class_2988.java:20)
	at net.minecraft.class_2988.method_13151(class_2988.java:13)
	at net.minecraft.class_2975.method_12862(class_2975.java:44)

-- Feature --
Details:
	Id: minecraft:decorated
	Config: < class_2986 [earthtojavamobs:mud_lake | minecraft:water_lake] >
	Description: < class_2988 [minecraft:decorated] >
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:575)

-- Generation --
Details:
	CenterX: 13
	CenterZ: -2
	Step: LOCAL_MODIFICATIONS
	Seed: 6215384374742343972
	Biome: minecraft:plains
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:210)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$1796/1804934885.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)

-- Chunk to be generated --
Details:
	Location: 13,-2
	Position hash: -8589934579
	Generator: net.minecraft.class_3754@4e63eebc
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$4994/1093055106.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$4979/349904103.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$4992/1457885555.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (216,64,-24), Chunk: (at 8,4,8 in 13,-2; contains blocks 208,0,-32 to 223,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:386)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:334)
	at net.minecraft.class_1132.method_3823(class_1132.java:69)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:647)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$4885/1263304408.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1451711160 bytes (1384 MB) / 4462739456 bytes (4256 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.0+1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		better_wither_skeletons: Better Wither Skeletons 1.1.0
		betterdroppeditems: Better Dropped Items 1.2.1-1.16
		bettereating: Better Eating 0.2.0
		betterf3: BetterF3 1.1.1
		blackstonetools: Blackstone Tools 1.0.1+1.16.1
		blast: BLAST 1.3.2
		blockus: Blockus 1.6.2
		bookworm: Bookworm Library 3.0.1
		caelus: Caelus API 0.0.5-1.16.1
		cardinal-components-base: Cardinal Components API (base) 2.4.0-nightly.1.16-rc1.build.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.0-nightly.1.16-rc1.build.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.0-nightly.1.16-rc1.build.2
		cavebiomes: Cave Biomes 0.2.3
		charcoalblock: Charcoal Block 1.0.1
		cherishedworlds: Cherished Worlds 1.0.1-1.16.1
		cinderscapes: Cinderscapes 1.0.5+build.36-1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.5
		cloth-config2: Cloth Config v4 4.6.0
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_json: json 3.6.3
		compactstatuseffects: Compact Status Effects 1.2.0
		compressedblocks: Compressed Blocks 1.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crimsonmoon: Crimson Moon 1.1.0-1.16
		crookedcrooks: Crooked Crooks 1.2.1+1.16.1
		curses: Curses 1.3.1
		dark-loading-screen: Dark Loading Screen 1.3.2
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		earthtojavamobs: Earth2Java 1.1.0+1.16.1
		enchantablehorsearmor: Enchantable Horse Armor 1.0a
		fabriblocks: FabriBlocks 1.2.0
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.10.3+build.211
		fabriczero: Fabric Zero 0.1.2
		flesh2leather: Flesh2Leather 1.0.0
		flight_display: Critical Flight Display 1.1.2
		goldenberries: Golden Berries 1.0.1
		gravestones: Gravestones 1.4.0
		horsestatsvanilla: Horse Stats Vanilla 3.0.0
		howlingwolves: Howling Wolves 1.0.0+build.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		infinityfix: Infinity Fix 1.1.0
		itemmodelfix: Item Model Fix 0.1.1
		jankson: Jankson 3.0.0+j1.2.0
		koi: Koi Fish 1.0.1
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		lapisreserve: Lapis Reserve 1.0.3
		libcd: LibCapableData 2.5.0+1.16.1
		libstructure: Libstructure 1.3
		logical_zoom: Logical Zoom 0.0.4
		maelstrom_library: Maelstrom Library 0.4
		magic_mirror: Magic Mirror 1.0.1
		mambience: MAmbience 2.1.0-1.16
		mighty_mangoes: Mighty Mangoes 1.0.0
		minecraft: Minecraft 1.16.1
		minimalmenu: MinimalMenu 1.16.1-0.0.4
		mm: Manningham Mills 2.0
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2-1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		mooblooms: Mooblooms 1.3.1
		moreberries: More Berries 1.3.1
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.0
		morepotions: More Potions 1.0.0
		moretotems: More Totems 2.5
		nbtcrafting: NBT Crafting 2.0.0-beta.1+mc1.16.1
		netherited: Netherited 0.8.1
		netheritehorsearmor: Netherite Horse Armor 0.3.1
		no_sneaking_over_magma: No Sneaking Over Magma! 1.0.2+1.16.1
		noexpensive: NoExpensive 1.16.1-Fabric-1.1.3
		notrample: No Trample 0.0.1
		now-playing: Now Playing 1.1.2
		onsoulfire: On Soul Fire r3
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		p3utils: P3NG00's Utilities 0.0.0
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		polymorph: Polymorph 0.0.2-1.16.1
		pumice: Pumice 0.0.1
		rainbucket: Rain Bucket 1.0.0
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		realisticfirespread: Realistic Fire Spread r1
		roughlyenoughitems: Roughly Enough Items 4.10.2
		roughlyenoughresources: Roughly Enough Resources 2.0.2
		sand_dust: Sand Dust 1.2.0
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		shapes: Shapes 2.0.0+build.10
		slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
		snowdrift: Snowdrift ${version}
		sodium: Sodium 0.1.0
		soulsandstone: Soul Sandstone 0.0.1
		soulsoilfarmland: Soul Soil Farmland 0.0.1
		spruceui: SpruceUI 1.5.8
		terraform: Terraform 2.1.7+build.31
		tinyfuel: Tiny Fuel 0.3.0
		torridvision: Torrid Vision 0.0.1
		trajectoryfabric: Trajectory Fabric 1.0.8
		trumpet-skeleton: Trumpet Skeleton 1.1.2
		waila: Hwyla 1.9.22
		water-erosion: Water Erosion 1.1.1
		whiteglowstone: White Glowstone 1.0.2
		wolveswitharmor: Wolves With Armor 1.4.0-1.16.1
		woods_and_mires: Woods and Mires 1.0.0+1.16.1
		zoob: Monster Of The Ocean Depths 1.0.0
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), fabric/lambdynlights, fabric/blackstonetools, fabric/iamverysmart, fabric/whiteglowstone, fabric/moretotems, fabric/morecraftingtables, fabric/pumice, fabric/fabric-tool-attribute-api-v1, fabric/rare-ice, fabric/blockus, fabric/soulsandstone, fabric/blast, fabric/earthtojavamobs, fabric/koi, fabric/libcd, fabric/flesh2leather, fabric/sand_dust, fabric/netherited, fabric/netheritehorsearmor, fabric/wolveswitharmor, fabric/goldenberries, fabric/charcoalblock, fabric/tinyfuel (incompatible), fabric/fabriblocks (incompatible), fabric/beachslimes, fabric/moreberries, fabric/compressedblocks, fabric/crookedcrooks, fabric/trumpet-skeleton (incompatible), fabric/woods_and_mires, fabric/soulsoilfarmland, fabric/mooblooms, fabric/gravestones, fabric/zoob, fabric/cinderscapes, fabric/better_wither_skeletons, fabric/mighty_mangoes, fabric/magic_mirror
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by CorgiTaco** [comment]
Looks to me this is a world gen mod issue as this is going on about feature placement. And it's pointing to ` Config: < class_2986 [earthtojavamobs:mud_lake | minecraft:water_lake] >` so report it to earthtojava. And it seems to be claiming they're using a negative number or 0 as a number random next int too
